#Variables:
#

#Executables
ASTAR_EXEC = test_AStar
DSTAR_EXEC = test_DStar

#Source Files
Dijkstra = dijkstra.cpp
AStar = a_star.cpp
DStar = d_star.cpp

#System
CC = gcc
CFLAGS = -03 -std=XXX -Wall -Wextra -Wshadow

#
#----------------------
#
#RULES:
$(ASTAR_EXEC) : $(AStar) $(Dijkstra) $(DStar)


# test_AStar: $(AStar) $(Dijkstra) $(DStar)
#  $(CC) $(AStar) $(Dijkstra) $(DStar) $(CFLAGS) -o $(ASTAR_EXEC)

# test_DStar: $(AStar) $(Dijkstra) $(DStar)
#  $(CC) $(AStar) $(Dijkstra) $(DStar) $(CFLAGS) -o $(DSTAR_EXEC)
